---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: database
  labels:
    app: pgbouncer
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp
      port: 5439
      targetPort: tcp
  selector:
    app: pgbouncer